---
- hosts: localhost
  gather_facts: false
  vars:
    metadata:
      name: Check if latest version of packages is installed
      description: >
        Makes sure a list of packages are at its latest version
        before starting an upgrade.
      groups:
        - pre-upgrade
  roles:
    - check_latest_packages_version
